host = "localhost"
port = 8080
env = "dev"
astro_port = 5431
prod_astro_build = true
cors_url = "http://localhost:5431"

[public_keys]
public_api_url = "http://localhost:8080/api"
public_ws_url = "ws://localhost:8080/ws/"